/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as CashierRouteImport } from "./routes/cashier";
import { Route as AdminIndexRouteImport } from "./routes/admin.index";
import { Route as AdminAcademicYearsRouteImport } from "./routes/admin.academic-years";
import { Route as AdminAdmissionsRouteImport } from "./routes/admin.admissions";
import { Route as AdminCashiersRouteImport } from "./routes/admin.cashiers";
import { Route as AdminClassesRouteImport } from "./routes/admin.classes";
import { Route as AdminDashboardRouteImport } from "./routes/admin.dashboard";
import { Route as AdminFeeCollectionRouteImport } from "./routes/admin.fee-collection";
import { Route as AdminFeeStructureRouteImport } from "./routes/admin.fee-structure";
import { Route as AdminFeeTermsRouteImport } from "./routes/admin.fee-terms";
import { Route as AdminPaymentsRouteImport } from "./routes/admin.payments";
import { Route as AdminReceiptsRouteImport } from "./routes/admin.receipts";
import { Route as AdminReportsRouteImport } from "./routes/admin.reports";
import { Route as AdminSettingsRouteImport } from "./routes/admin.settings";
import { Route as CashierIndexRouteImport } from "./routes/cashier.index";
import { Route as CashierDashboardRouteImport } from "./routes/cashier.dashboard";
import { Route as CashierFeeCollectionRouteImport } from "./routes/cashier.fee-collection";
import { Route as CashierPaymentsRouteImport } from "./routes/cashier.payments";
import { Route as CashierReceiptsRouteImport } from "./routes/cashier.receipts";
import { Route as CashierReportsRouteImport } from "./routes/cashier.reports";
import { Route as AdminStudentsIndexRouteImport } from "./routes/admin.students.index";
import { Route as AdminStudentsIdRouteImport } from "./routes/admin.students.$id";
import { Route as CashierStudentsIndexRouteImport } from "./routes/cashier.students.index";
import { Route as CashierStudentsIdRouteImport } from "./routes/cashier.students.$id";
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
});
const CashierRoute = CashierRouteImport.update({
  id: "/cashier",
  path: "/cashier",
  getParentRoute: () => rootRouteImport,
});
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRoute,
});
const AdminAcademicYearsRoute = AdminAcademicYearsRouteImport.update({
  id: "/academic-years",
  path: "/academic-years",
  getParentRoute: () => AdminRoute,
});
const AdminAdmissionsRoute = AdminAdmissionsRouteImport.update({
  id: "/admissions",
  path: "/admissions",
  getParentRoute: () => AdminRoute,
});
const AdminCashiersRoute = AdminCashiersRouteImport.update({
  id: "/cashiers",
  path: "/cashiers",
  getParentRoute: () => AdminRoute,
});
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: "/classes",
  path: "/classes",
  getParentRoute: () => AdminRoute,
});
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AdminRoute,
});
const AdminFeeCollectionRoute = AdminFeeCollectionRouteImport.update({
  id: "/fee-collection",
  path: "/fee-collection",
  getParentRoute: () => AdminRoute,
});
const AdminFeeStructureRoute = AdminFeeStructureRouteImport.update({
  id: "/fee-structure",
  path: "/fee-structure",
  getParentRoute: () => AdminRoute,
});
const AdminFeeTermsRoute = AdminFeeTermsRouteImport.update({
  id: "/fee-terms",
  path: "/fee-terms",
  getParentRoute: () => AdminRoute,
});
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: "/payments",
  path: "/payments",
  getParentRoute: () => AdminRoute,
});
const AdminReceiptsRoute = AdminReceiptsRouteImport.update({
  id: "/receipts",
  path: "/receipts",
  getParentRoute: () => AdminRoute,
});
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => AdminRoute,
});
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AdminRoute,
});
const CashierIndexRoute = CashierIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => CashierRoute,
});
const CashierDashboardRoute = CashierDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => CashierRoute,
});
const CashierFeeCollectionRoute = CashierFeeCollectionRouteImport.update({
  id: "/fee-collection",
  path: "/fee-collection",
  getParentRoute: () => CashierRoute,
});
const CashierPaymentsRoute = CashierPaymentsRouteImport.update({
  id: "/payments",
  path: "/payments",
  getParentRoute: () => CashierRoute,
});
const CashierReceiptsRoute = CashierReceiptsRouteImport.update({
  id: "/receipts",
  path: "/receipts",
  getParentRoute: () => CashierRoute,
});
const CashierReportsRoute = CashierReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => CashierRoute,
});
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: "/students/",
  path: "/students/",
  getParentRoute: () => AdminRoute,
});
const AdminStudentsIdRoute = AdminStudentsIdRouteImport.update({
  id: "/students/$id",
  path: "/students/$id",
  getParentRoute: () => AdminRoute,
});
const CashierStudentsIndexRoute = CashierStudentsIndexRouteImport.update({
  id: "/students/",
  path: "/students/",
  getParentRoute: () => CashierRoute,
});
const CashierStudentsIdRoute = CashierStudentsIdRouteImport.update({
  id: "/students/$id",
  path: "/students/$id",
  getParentRoute: () => CashierRoute,
});
const AdminRouteChildren = {
  AdminAcademicYearsRoute: AdminAcademicYearsRoute,
  AdminAdmissionsRoute: AdminAdmissionsRoute,
  AdminCashiersRoute: AdminCashiersRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFeeCollectionRoute: AdminFeeCollectionRoute,
  AdminFeeStructureRoute: AdminFeeStructureRoute,
  AdminFeeTermsRoute: AdminFeeTermsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReceiptsRoute: AdminReceiptsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminStudentsIdRoute: AdminStudentsIdRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
};
const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);
const CashierRouteChildren = {
  CashierDashboardRoute: CashierDashboardRoute,
  CashierFeeCollectionRoute: CashierFeeCollectionRoute,
  CashierPaymentsRoute: CashierPaymentsRoute,
  CashierReceiptsRoute: CashierReceiptsRoute,
  CashierReportsRoute: CashierReportsRoute,
  CashierIndexRoute: CashierIndexRoute,
  CashierStudentsIdRoute: CashierStudentsIdRoute,
  CashierStudentsIndexRoute: CashierStudentsIndexRoute,
};
const CashierRouteWithChildren = CashierRoute._addFileChildren(CashierRouteChildren);
const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CashierRoute: CashierRouteWithChildren,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
