/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CashierRouteImport } from './routes/cashier'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAcademicYearsRouteImport } from './routes/admin.academic-years'
import { Route as AdminAdmissionsRouteImport } from './routes/admin.admissions'
import { Route as AdminCashiersRouteImport } from './routes/admin.cashiers'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminFeeCollectionRouteImport } from './routes/admin.fee-collection'
import { Route as AdminFeeStructureRouteImport } from './routes/admin.fee-structure'
import { Route as AdminFeeTermsRouteImport } from './routes/admin.fee-terms'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminReceiptsRouteImport } from './routes/admin.receipts'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as CashierIndexRouteImport } from './routes/cashier.index'
import { Route as CashierDashboardRouteImport } from './routes/cashier.dashboard'
import { Route as CashierFeeCollectionRouteImport } from './routes/cashier.fee-collection'
import { Route as CashierPaymentsRouteImport } from './routes/cashier.payments'
import { Route as CashierReceiptsRouteImport } from './routes/cashier.receipts'
import { Route as CashierReportsRouteImport } from './routes/cashier.reports'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin.students.index'
import { Route as AdminStudentsIdRouteImport } from './routes/admin.students.$id'
import { Route as CashierStudentsIndexRouteImport } from './routes/cashier.students.index'
import { Route as CashierStudentsIdRouteImport } from './routes/cashier.students.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierRoute = CashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademicYearsRoute = AdminAcademicYearsRouteImport.update({
  id: '/academic-years',
  path: '/academic-years',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdmissionsRoute = AdminAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCashiersRoute = AdminCashiersRouteImport.update({
  id: '/cashiers',
  path: '/cashiers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeeCollectionRoute = AdminFeeCollectionRouteImport.update({
  id: '/fee-collection',
  path: '/fee-collection',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeeStructureRoute = AdminFeeStructureRouteImport.update({
  id: '/fee-structure',
  path: '/fee-structure',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeeTermsRoute = AdminFeeTermsRouteImport.update({
  id: '/fee-terms',
  path: '/fee-terms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceiptsRoute = AdminReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const CashierIndexRoute = CashierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CashierRoute,
} as any)
const CashierDashboardRoute = CashierDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CashierRoute,
} as any)
const CashierFeeCollectionRoute = CashierFeeCollectionRouteImport.update({
  id: '/fee-collection',
  path: '/fee-collection',
  getParentRoute: () => CashierRoute,
} as any)
const CashierPaymentsRoute = CashierPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => CashierRoute,
} as any)
const CashierReceiptsRoute = CashierReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => CashierRoute,
} as any)
const CashierReportsRoute = CashierReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => CashierRoute,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsIdRoute = AdminStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AdminRoute,
} as any)
const CashierStudentsIndexRoute = CashierStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => CashierRoute,
} as any)
const CashierStudentsIdRoute = CashierStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => CashierRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cashier': typeof CashierRouteWithChildren
  '/admin/academic-years': typeof AdminAcademicYearsRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/cashiers': typeof AdminCashiersRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fee-collection': typeof AdminFeeCollectionRoute
  '/admin/fee-structure': typeof AdminFeeStructureRoute
  '/admin/fee-terms': typeof AdminFeeTermsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/cashier/dashboard': typeof CashierDashboardRoute
  '/cashier/fee-collection': typeof CashierFeeCollectionRoute
  '/cashier/payments': typeof CashierPaymentsRoute
  '/cashier/receipts': typeof CashierReceiptsRoute
  '/cashier/reports': typeof CashierReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/cashier/': typeof CashierIndexRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/cashier/students/$id': typeof CashierStudentsIdRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/cashier/students/': typeof CashierStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/academic-years': typeof AdminAcademicYearsRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/cashiers': typeof AdminCashiersRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fee-collection': typeof AdminFeeCollectionRoute
  '/admin/fee-structure': typeof AdminFeeStructureRoute
  '/admin/fee-terms': typeof AdminFeeTermsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/cashier/dashboard': typeof CashierDashboardRoute
  '/cashier/fee-collection': typeof CashierFeeCollectionRoute
  '/cashier/payments': typeof CashierPaymentsRoute
  '/cashier/receipts': typeof CashierReceiptsRoute
  '/cashier/reports': typeof CashierReportsRoute
  '/admin': typeof AdminIndexRoute
  '/cashier': typeof CashierIndexRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/cashier/students/$id': typeof CashierStudentsIdRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/cashier/students': typeof CashierStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cashier': typeof CashierRouteWithChildren
  '/admin/academic-years': typeof AdminAcademicYearsRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/cashiers': typeof AdminCashiersRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fee-collection': typeof AdminFeeCollectionRoute
  '/admin/fee-structure': typeof AdminFeeStructureRoute
  '/admin/fee-terms': typeof AdminFeeTermsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/cashier/dashboard': typeof CashierDashboardRoute
  '/cashier/fee-collection': typeof CashierFeeCollectionRoute
  '/cashier/payments': typeof CashierPaymentsRoute
  '/cashier/receipts': typeof CashierReceiptsRoute
  '/cashier/reports': typeof CashierReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/cashier/': typeof CashierIndexRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/cashier/students/$id': typeof CashierStudentsIdRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/cashier/students/': typeof CashierStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cashier'
    | '/admin/academic-years'
    | '/admin/admissions'
    | '/admin/cashiers'
    | '/admin/classes'
    | '/admin/dashboard'
    | '/admin/fee-collection'
    | '/admin/fee-structure'
    | '/admin/fee-terms'
    | '/admin/payments'
    | '/admin/receipts'
    | '/admin/reports'
    | '/admin/settings'
    | '/cashier/dashboard'
    | '/cashier/fee-collection'
    | '/cashier/payments'
    | '/cashier/receipts'
    | '/cashier/reports'
    | '/admin/'
    | '/cashier/'
    | '/admin/students/$id'
    | '/cashier/students/$id'
    | '/admin/students/'
    | '/cashier/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/academic-years'
    | '/admin/admissions'
    | '/admin/cashiers'
    | '/admin/classes'
    | '/admin/dashboard'
    | '/admin/fee-collection'
    | '/admin/fee-structure'
    | '/admin/fee-terms'
    | '/admin/payments'
    | '/admin/receipts'
    | '/admin/reports'
    | '/admin/settings'
    | '/cashier/dashboard'
    | '/cashier/fee-collection'
    | '/cashier/payments'
    | '/cashier/receipts'
    | '/cashier/reports'
    | '/admin'
    | '/cashier'
    | '/admin/students/$id'
    | '/cashier/students/$id'
    | '/admin/students'
    | '/cashier/students'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cashier'
    | '/admin/academic-years'
    | '/admin/admissions'
    | '/admin/cashiers'
    | '/admin/classes'
    | '/admin/dashboard'
    | '/admin/fee-collection'
    | '/admin/fee-structure'
    | '/admin/fee-terms'
    | '/admin/payments'
    | '/admin/receipts'
    | '/admin/reports'
    | '/admin/settings'
    | '/cashier/dashboard'
    | '/cashier/fee-collection'
    | '/cashier/payments'
    | '/cashier/receipts'
    | '/cashier/reports'
    | '/admin/'
    | '/cashier/'
    | '/admin/students/$id'
    | '/cashier/students/$id'
    | '/admin/students/'
    | '/cashier/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CashierRoute: typeof CashierRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier': {
      id: '/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof CashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academic-years': {
      id: '/admin/academic-years'
      path: '/academic-years'
      fullPath: '/admin/academic-years'
      preLoaderRoute: typeof AdminAcademicYearsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admissions': {
      id: '/admin/admissions'
      path: '/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AdminAdmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cashiers': {
      id: '/admin/cashiers'
      path: '/cashiers'
      fullPath: '/admin/cashiers'
      preLoaderRoute: typeof AdminCashiersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fee-collection': {
      id: '/admin/fee-collection'
      path: '/fee-collection'
      fullPath: '/admin/fee-collection'
      preLoaderRoute: typeof AdminFeeCollectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fee-structure': {
      id: '/admin/fee-structure'
      path: '/fee-structure'
      fullPath: '/admin/fee-structure'
      preLoaderRoute: typeof AdminFeeStructureRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fee-terms': {
      id: '/admin/fee-terms'
      path: '/fee-terms'
      fullPath: '/admin/fee-terms'
      preLoaderRoute: typeof AdminFeeTermsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receipts': {
      id: '/admin/receipts'
      path: '/receipts'
      fullPath: '/admin/receipts'
      preLoaderRoute: typeof AdminReceiptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cashier/': {
      id: '/cashier/'
      path: '/'
      fullPath: '/cashier/'
      preLoaderRoute: typeof CashierIndexRouteImport
      parentRoute: typeof CashierRoute
    }
    '/cashier/dashboard': {
      id: '/cashier/dashboard'
      path: '/dashboard'
      fullPath: '/cashier/dashboard'
      preLoaderRoute: typeof CashierDashboardRouteImport
      parentRoute: typeof CashierRoute
    }
    '/cashier/fee-collection': {
      id: '/cashier/fee-collection'
      path: '/fee-collection'
      fullPath: '/cashier/fee-collection'
      preLoaderRoute: typeof CashierFeeCollectionRouteImport
      parentRoute: typeof CashierRoute
    }
    '/cashier/payments': {
      id: '/cashier/payments'
      path: '/payments'
      fullPath: '/cashier/payments'
      preLoaderRoute: typeof CashierPaymentsRouteImport
      parentRoute: typeof CashierRoute
    }
    '/cashier/receipts': {
      id: '/cashier/receipts'
      path: '/receipts'
      fullPath: '/cashier/receipts'
      preLoaderRoute: typeof CashierReceiptsRouteImport
      parentRoute: typeof CashierRoute
    }
    '/cashier/reports': {
      id: '/cashier/reports'
      path: '/reports'
      fullPath: '/cashier/reports'
      preLoaderRoute: typeof CashierReportsRouteImport
      parentRoute: typeof CashierRoute
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/$id': {
      id: '/admin/students/$id'
      path: '/students/$id'
      fullPath: '/admin/students/$id'
      preLoaderRoute: typeof AdminStudentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cashier/students/': {
      id: '/cashier/students/'
      path: '/students'
      fullPath: '/cashier/students/'
      preLoaderRoute: typeof CashierStudentsIndexRouteImport
      parentRoute: typeof CashierRoute
    }
    '/cashier/students/$id': {
      id: '/cashier/students/$id'
      path: '/students/$id'
      fullPath: '/cashier/students/$id'
      preLoaderRoute: typeof CashierStudentsIdRouteImport
      parentRoute: typeof CashierRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAcademicYearsRoute: typeof AdminAcademicYearsRoute
  AdminAdmissionsRoute: typeof AdminAdmissionsRoute
  AdminCashiersRoute: typeof AdminCashiersRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFeeCollectionRoute: typeof AdminFeeCollectionRoute
  AdminFeeStructureRoute: typeof AdminFeeStructureRoute
  AdminFeeTermsRoute: typeof AdminFeeTermsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReceiptsRoute: typeof AdminReceiptsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminStudentsIdRoute: typeof AdminStudentsIdRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcademicYearsRoute: AdminAcademicYearsRoute,
  AdminAdmissionsRoute: AdminAdmissionsRoute,
  AdminCashiersRoute: AdminCashiersRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFeeCollectionRoute: AdminFeeCollectionRoute,
  AdminFeeStructureRoute: AdminFeeStructureRoute,
  AdminFeeTermsRoute: AdminFeeTermsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReceiptsRoute: AdminReceiptsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminStudentsIdRoute: AdminStudentsIdRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CashierRouteChildren {
  CashierDashboardRoute: typeof CashierDashboardRoute
  CashierFeeCollectionRoute: typeof CashierFeeCollectionRoute
  CashierPaymentsRoute: typeof CashierPaymentsRoute
  CashierReceiptsRoute: typeof CashierReceiptsRoute
  CashierReportsRoute: typeof CashierReportsRoute
  CashierIndexRoute: typeof CashierIndexRoute
  CashierStudentsIdRoute: typeof CashierStudentsIdRoute
  CashierStudentsIndexRoute: typeof CashierStudentsIndexRoute
}

const CashierRouteChildren: CashierRouteChildren = {
  CashierDashboardRoute: CashierDashboardRoute,
  CashierFeeCollectionRoute: CashierFeeCollectionRoute,
  CashierPaymentsRoute: CashierPaymentsRoute,
  CashierReceiptsRoute: CashierReceiptsRoute,
  CashierReportsRoute: CashierReportsRoute,
  CashierIndexRoute: CashierIndexRoute,
  CashierStudentsIdRoute: CashierStudentsIdRoute,
  CashierStudentsIndexRoute: CashierStudentsIndexRoute,
}

const CashierRouteWithChildren =
  CashierRoute._addFileChildren(CashierRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CashierRoute: CashierRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
